import express from "express";
import cors  from "cors";
import dbConnection from "./dataBase/DbConfig.js";
import route from "./Routes/routes.js";
const PORT = process.env.PORT|| 3500;
const app = express();
app.use(express.json());
app.use(cors());
dbConnection();
app.use('/', route);
app.listen(PORT, () => console.log(`App is running on port no:${PORT}`));